"airplanes/frames/frame5.jpeg@0";
"airplanes/frames/frame6.jpeg@1";
"airplanes/frames/frame7.jpeg@2";
"airplanes/frames/frame8.jpeg@3";
"airplanes/frames/frame9.jpeg@4";
"airplanes/frames/frame10.jpeg@5";
"airplanes/frames/frame11.jpeg@6";
"airplanes/frames/frame12.jpeg@7";
"airplanes/frames/frame13.jpeg@8";
"airplanes/frames/frame14.jpeg@9";
"airplanes/frames/frame15.jpeg@10";
"airplanes/frames/frame16.jpeg@11";
"airplanes/frames/frame17.jpeg@12";
"airplanes/frames/frame18.jpeg@13";
"airplanes/frames/frame19.jpeg@14";
"airplanes/frames/frame20.jpeg@15";
"airplanes/frames/frame21.jpeg@16";
"airplanes/frames/frame22.jpeg@17";
"airplanes/frames/frame23.jpeg@18";
"airplanes/frames/frame24.jpeg@19";
"airplanes/frames/frame25.jpeg@20";
"airplanes/frames/frame26.jpeg@21";
"airplanes/frames/frame27.jpeg@22";
"airplanes/frames/frame28.jpeg@23";
"airplanes/frames/frame29.jpeg@24";
"airplanes/frames/frame30.jpeg@25";
"airplanes/frames/frame31.jpeg@26";
"airplanes/frames/frame32.jpeg@27";
"airplanes/frames/frame33.jpeg@28";
"airplanes/frames/frame34.jpeg@29";
"airplanes/frames/frame35.jpeg@30";
"airplanes/frames/frame36.jpeg@31";
"airplanes/frames/frame37.jpeg@32";
"airplanes/frames/frame38.jpeg@33";
"airplanes/frames/frame39.jpeg@34";
"airplanes/frames/frame40.jpeg@35";
"airplanes/frames/frame41.jpeg@36";
"airplanes/frames/frame42.jpeg@37";
"airplanes/frames/frame43.jpeg@38";
"airplanes/frames/frame44.jpeg@39": (139.461326599, 221.098812103, 254.538673401, 346.901187897):0.918095;
"airplanes/frames/frame45.jpeg@40";
"airplanes/frames/frame46.jpeg@41";
"airplanes/frames/frame47.jpeg@42";
"airplanes/frames/frame48.jpeg@43";
"airplanes/frames/frame49.jpeg@44": (-15.3557701111, 359.503578186, 37.3557701111, 550.496421814):0.967659;
"airplanes/frames/frame50.jpeg@45";
"airplanes/frames/frame51.jpeg@46";
"airplanes/frames/frame52.jpeg@47";
"airplanes/frames/frame53.jpeg@48";
"airplanes/frames/frame54.jpeg@49";
"airplanes/frames/frame55.jpeg@50";
"airplanes/frames/frame56.jpeg@51";
"airplanes/frames/frame57.jpeg@52";
"airplanes/frames/frame58.jpeg@53";
"airplanes/frames/frame59.jpeg@54": (-31.0738372803, 374.633552551, 11.0738372803, 547.366447449):0.962813, (-31.4459323883, 382.540496826, 13.4459323883, 559.459503174):0.903579;
"airplanes/frames/frame60.jpeg@55";
"airplanes/frames/frame61.jpeg@56";
"airplanes/frames/frame62.jpeg@57": (-25.5075130463, 375.168457031, 17.5075130463, 548.831542969):0.993114, (-25.1506385803, 381.207832336, 19.1506385803, 558.792167664):0.996849;
"airplanes/frames/frame63.jpeg@58";
"airplanes/frames/frame64.jpeg@59";
"airplanes/frames/frame65.jpeg@60";
"airplanes/frames/frame66.jpeg@61";
"airplanes/frames/frame67.jpeg@62";
"airplanes/frames/frame68.jpeg@63";
"airplanes/frames/frame69.jpeg@64";
"airplanes/frames/frame70.jpeg@65";
"airplanes/frames/frame71.jpeg@66";
"airplanes/frames/frame72.jpeg@67";
"airplanes/frames/frame73.jpeg@68";
"airplanes/frames/frame74.jpeg@69";
"airplanes/frames/frame75.jpeg@70";
"airplanes/frames/frame76.jpeg@71";
"airplanes/frames/frame77.jpeg@72";
"airplanes/frames/frame78.jpeg@73";
"airplanes/frames/frame79.jpeg@74";
"airplanes/frames/frame80.jpeg@75";
"airplanes/frames/frame81.jpeg@76";
"airplanes/frames/frame82.jpeg@77";
"airplanes/frames/frame83.jpeg@78";
"airplanes/frames/frame84.jpeg@79";
"airplanes/frames/frame85.jpeg@80";
"airplanes/frames/frame86.jpeg@81";
"airplanes/frames/frame87.jpeg@82";
"airplanes/frames/frame88.jpeg@83";
"airplanes/frames/frame89.jpeg@84";
"airplanes/frames/frame90.jpeg@85";
"airplanes/frames/frame91.jpeg@86";
"airplanes/frames/frame92.jpeg@87";
"airplanes/frames/frame93.jpeg@88";
"airplanes/frames/frame94.jpeg@89";
"airplanes/frames/frame95.jpeg@90";
"airplanes/frames/frame96.jpeg@91";
"airplanes/frames/frame97.jpeg@92";
"airplanes/frames/frame98.jpeg@93";
"airplanes/frames/frame99.jpeg@94";
"airplanes/frames/frame100.jpeg@95";
"airplanes/frames/frame101.jpeg@96";
"airplanes/frames/frame102.jpeg@97";
"airplanes/frames/frame103.jpeg@98";
"airplanes/frames/frame104.jpeg@99";
"airplanes/frames/frame105.jpeg@100";
"airplanes/frames/frame106.jpeg@101";
"airplanes/frames/frame107.jpeg@102";
"airplanes/frames/frame108.jpeg@103";
"airplanes/frames/frame109.jpeg@104";
"airplanes/frames/frame110.jpeg@105";
"airplanes/frames/frame111.jpeg@106";
"airplanes/frames/frame112.jpeg@107";
"airplanes/frames/frame113.jpeg@108";
"airplanes/frames/frame114.jpeg@109";
"airplanes/frames/frame115.jpeg@110";
"airplanes/frames/frame116.jpeg@111";
"airplanes/frames/frame117.jpeg@112";
"airplanes/frames/frame118.jpeg@113";
"airplanes/frames/frame119.jpeg@114";
"airplanes/frames/frame120.jpeg@115";
"airplanes/frames/frame121.jpeg@116";
"airplanes/frames/frame122.jpeg@117";
"airplanes/frames/frame123.jpeg@118".
